name: chirag_css_programming
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- conda-forge::ca-certificates=2020.4.5.1=hecc5488_0
- conda-forge::certifi=2020.4.5.1=py36h9f0ad1d_0
- conda-forge::libcxx=10.0.0=0
- conda-forge::libffi=3.2.1=h4a8c4bd_1007
- conda-forge::ncurses=6.1=h0a44026_1002
- conda-forge::openssl=1.1.1f=h0b31af3_0
- conda-forge::pip=20.0.2=py_2
- conda-forge::python=3.6.10=hd6c0276_1010_cpython
- conda-forge::python_abi=3.6=1_cp36m
- conda-forge::readline=8.0=hcfe32e1_0
- conda-forge::setuptools=46.1.3=py36h9f0ad1d_0
- conda-forge::sqlite=3.30.1=h93121df_0
- conda-forge::tk=8.6.10=hbbe82c9_0
- conda-forge::wheel=0.34.2=py_1
- conda-forge::xz=5.2.5=h0b31af3_0
- conda-forge::zlib=1.2.11=h0b31af3_1006
prefix: /Users/chiragmahapatra/miniconda3/envs/chirag_css_programming

